
export const m = [
  "black",
  "black and white",
  "calico",
  "dilute calico",
  "chocolate",
  "chocolate and white",
  "cinnamon and white",
  "cinnamon",
  "cream",
  "cream and white",
  "colorpoint",
  "fawn",
  "fawn and white",
  "gray",
  "gray and white",
  "lilac",
  "lilac and white",
  "longhair",
  "mink",
  "orange",
  "orange and white",
  "sepia",
  "shorthair",
  "tabby",
  "tortoiseshell",
  "dilute tortoiseshell",
  "tortoiseshell and white",
  "dilute tortoiseshell and white",
  "white",
]

// array of valid cat colors 
export const colors = [
  "black",
  "black and white",
  "calico",
  "blue calico",
  "gray calico",
  "chocolate calico",
  "cinnamon calico",
  "lilac calico",
  "fawn calico",
  "chocolate",
  "chocolate and white",
  "cinnamon",
  "cinnamon and white",
  "cream",
  "cream and white",
  "fawn",
  "fawn and white",
  "gray",
  "gray and white",
  // "lavender",
  // "lavender and white",
  "lilac",
  "lilac and white",
  "orange",
  "orange and white",
  "tortoiseshell", // i.e., black and orange 
  "gray tortoiseshell", // dilute black and orange = blue and cream 
  "blue tortoiseshell", // dilute black and orange = blue and cream 
  "chocolate tortoiseshell", // brown and orange 
  "cinnamon tortoiseshell", // cinnamon and orange 
  "lilac tortoiseshell", // light brown and cream 
  "fawn tortoiseshell", // light cinnamon and cream 
  "tortoiseshell and white",
  "dilute tortoiseshell and white",
  "white",
]

export const coatTypes = [
  "hairless", 
  "longhair", 
  "rex", 
  "shorthair", 
]

export const coatPatterns = [
  "bicolor",
  "colorpoint",
  "mink", // a less-contrasting form of colorpoint, created by crossing Siamese with Burmese 
  "sepia", // color pattern seen in Burmese 
  "tabby",
  "tricolor", // another name for tortoiseshell / calico 
]

export const validColors : { [key: string]: string; } = {
  "tortie": "tortoiseshell", 
  "dilute tortie": "dilute tortoiseshell", 
  "tortoiseshell": "tortoiseshell", 
  "white": "white", 
  "black": "black", 
  "gray": "gray", 
  "grey": "gray", 
  "blue": "gray", 
  "red": "orange", 
  "orange": "orange", 
  "ginger": "orange", 
  "cream": "cream", 
  "dilute orange": "cream", 
  "chocolate": "chocolate", 
  "cinnamon": "cinnamon", 
  "lilac": "lilac", 
  "lavender": "lilac", 
  "fawn": "fawn", 
}

export const validCoatTypes : { [key: string]: string; } = {
  "longhair": "longhair", 
  "long hair": "longhair", 
  "shorthair": "shorthair", 
  "short hair": "shorthair", 
}

export const validCoatPatterns : { [key: string]: string; } = {
  "tabby": "tabby",
  "tuxedo": "bicolor",
  "tuxie": "bicolor",
  // "calico": "bicolor",
  "bicolor": "bicolor",
  "bicolour": "bicolor",
  "mink": "mink",
  "tonkinese colorpoint": "mink",
  "sepia": "sepia",
  "burmese colorpoint": "sepia",
  "colorpoint": "colorpoint",
  "color point": "colorpoint",
  "colourpoint": "colorpoint",
  "colour point": "colorpoint",
  "pointed": "colorpoint",
}

// To Do: add more breeds
export const breeds : string[] = [
  "Abyssinian",
  "Angora",
  "Balinese",
  "Birman",
  "Bombay",
  "Burmese",
  "Burmilla",
  "Devon Rex",
  "Egyptian Mau",
  "Havana Brown",
  "Himalayan",
  "Javanese",
  "Maine Coon",
  "Nebelung",
  "Neva Masquerade",
  "Norwegian Forest",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Thai",
  "Tiffanie",
  "Tonkinese",
  "Turkish",
]

// Because Tailwind doesn't understand dynamic class names. 
export const catTraitCSS : { [key: string]: string} = {
  "orange": "bg-orange",
  "orange and white": "bg-orange-w",
  "cream": "bg-cream",
  "cream and white": "bg-cream-w",
  "black": "bg-black text-white",
  "black and white": "bg-black-w",
  "gray": "bg-gray text-white",
  "gray and white": "bg-gray-w",
  "chocolate": "bg-chocolate text-white",
  "chocolate and white": "bg-chocolate-w",
  "lilac": "bg-lilac",
  "lilac and white": "bg-lilac-w",
  "cinnamon": "bg-cinnamon text-white",
  "cinnamon and white": "bg-cinnamon-w",
  "fawn": "bg-fawn",
  "fawn and white": "bg-fawn-w",
  "white": "bg-white",
  "calico": "bg-calico",
  "blue calico": "bg-calico-blue",
  "gray calico": "bg-calico-blue",
  "chocolate calico": "bg-calico-chocolate",
  "cinnamon calico": "bg-calico-cinnamon",
  "lilac calico": "bg-calico-lilac",
  "fawn calico": "bg-calico-fawn",
  "dilute calico": "bg-calico-d",
  "tortoiseshell": "bg-tortie",
  "blue tortoiseshell": "bg-tortie-blue",
  "gray tortoiseshell": "bg-tortie-blue",
  "chocolate tortoiseshell": "bg-tortie-chocolate text-white",
  "cinnamon tortoiseshell": "bg-tortie-cinnamon",
  "lilac tortoiseshell": "bg-tortie-lilac",
  "fawn tortoiseshell": "bg-tortie-fawn",
  "dilute tortoiseshell": "bg-tortie-d",
  "tortoiseshell-and-white": "bg-calico",
  "dilute-tortoiseshell-and-white": "bg-calico-blue",
}

// Mapping of gene name -> list of valid allele pairs 
// (Note that the letters used to represent alleles are not completely standardized and may be different in some textbooks and other sources.)
export const genes : { [key: string]: string[] } = {
  "White": ["WDWD", "WDWh", "WDw", "WhWh", "WhWl", "Whw", "WlWl", "Wlw", "ww"], 
  "Orange": ["OO", "O", "Oo", "oo", "o"],
  "Brown": ["BB", "Bb", "Bbl", "bb", "bbl", "blbl"], 
  "Dilute": ["DD", "Dd", "dd"], 
  "Agouti": ["AA", "Aa", "aa"], 
  "Colorpoint": ["CC", "Ccs", "Ccb", "Cc", "cscs", "csc", "cbcb", "cbc", "cscb", "cc"],
  "Longhair": ["LL", "Ll", "ll"]
}

export const superscriptMappings : {[key: string]: string} = {
  "ᴰ": "D",
  "ᵇ": "b",
  "ˡ": "l",
  "ʰ": "h", 
  "ˢ": "s"
}

// Gene representation for UI. 
export const genesFormatted : { [key: string]: string[] } = {
  "White": ["Wᴰ/Wᴰ", "Wᴰ/Wʰ", "Wᴰ/w", "Wʰ/Wʰ", "Wʰ/Wˡ", "Wʰ/w", "Wˡ/Wˡ", "Wˡ/w", "w/w"], 
  "Orange": ["O/O", "O", "O/o", "oo", "o"],
  "Brown": ["B/B", "B/b", "B/bˡ", "b/b", "b/bˡ", "bˡ/bˡ"], 
  "Dilute": ["D/D", "D/d", "d/d"], 
  "Agouti": ["A/A", "A/a", "a/a"], 
  "Colorpoint": ["C/C", "C/cˢ", "C/cᵇ", "C/c", "cˢ/cˢ", "cˢ/c", "cᵇ/cᵇ", "cᵇ/c", "cˢ/cᵇ", "c/c"],
  "Longhair": ["L/L", "L/l", "l/l"]
}

export const genesRawToFormatted : { [key: string]: string } = {
  "WDWD": "Wᴰ/Wᴰ", 
  "WDWh": "Wᴰ/Wʰ", 
  "WDw": "Wᴰ/w", 
  "WhWh": "Wʰ/Wʰ", 
  "WhWl": "Wʰ/Wˡ", 
  "Whw": "Wʰ/w", 
  "WlWl": "Wˡ/Wˡ", 
  "Wlw": "Wˡ/w",
  "ww": "w/w", 
  "OO": "O/O",
  "O": "O",
  "Oo": "O/o",
  "oo": "o/o",
  "o": "o",
  "BB": "B/B", 
  "Bb": "B/b",
  "Bbl": "B/bˡ", 
  "bb": "b/b", 
  "bbl": "b/bˡ", 
  "blbl": "bˡ/bˡ", 
  "DD": "D/D", 
  "Dd": "D/d", 
  "dd": "d/d", 
  "AA": "A/A", 
  "Aa": "A/a",
  "aa": "a/a", 
  "CC": "C/C", 
  "Cc": "C/c", 
  "Ccs": "C/cˢ", 
  "Ccb": "C/cᵇ", 
  "cscs": "cˢ/cˢ", 
  "csc": "cˢ/c", 
  "cbcb": "cᵇ/cᵇ", 
  "cbc": "cᵇ/c", 
  "cscb": "cˢ/cᵇ", 
  "cc": "c/c",
  "LL": "L/L",
  "Ll": "L/l", 
  "ll": "l/l",
  "XX": "X/X",
  "XY": "X/Y"
}

// Mapping of allele string -> array of alleles 
export const alleleMappings : { [key: string]: string[] } = {
  "XX": ["X", "X"],
  "XY": ["X", "Y"],
  "WDWD": ["WD", "WD"], 
  "WDWh": ["WD", "Wh"], 
  "WDw": ["WD", "w"], 
  "WhWh": ["Wh", "Wh"], 
  "WhWl": ["Wh", "Wl"], 
  "Whw": ["Wh", "w"], 
  "WlWl": ["Wl", "Wl"], 
  "Wlw": ["Wl", "w"],
  "ww": ["w", "w"],
  "OO": ["O", "O"],
  "Oo": ["O", "o"],
  "oo": ["o", "o"],
  "O": ["O"],
  "o": ["o"],
  "BB": ["B", "B"],
  "Bb": ["B", "b"],
  "Bbl": ["B", "bl"],
  "bb": ["b", "b"],
  "bbl": ["b", "bl"],
  "blbl": ["bl", "bl"],
  "DD": ["D", "D"],
  "Dd": ["D", "d"],
  "dd": ["d", "d"],
  "AA": ["A", "A"],
  "Aa": ["A", "a"],
  "aa": ["a", "a"],
  "CC": ["C", "C"], 
  "Cc": ["C", "c"], 
  "Ccs": ["C", "cs"], 
  "Ccb": ["C", "cb"], 
  "cscs": ["cs", "cs"], 
  "csc": ["cs", "c"], 
  "cscb": ["cs", "cb"], 
  "cbcb": ["cb", "cb"], 
  "cbc": ["cb", "c"], 
  "cc": ["c", "c"], 
  "LL": ["L", "L"], 
  "Ll": ["L", "l"], 
  "ll": ["l", "l"], 
}

// Explanations to show the user what each gene does. The current ordering is intended to be the most intuitive for teaching the user how they interact. 
// TODO: add rex and hairless
export const tooltips : { [key: string]: string} = {
  "White": "One or more copies of Wᴰ produces a solid white cat regardless of other genes. In a cat without Wᴰ, one or more copies of Wʰ causes large white markings such as the van pattern, whereas Wˡ in the absence of Wᴰ and Wʰ causes small white markings. A w/w cat has no white markings.",
  "Orange": "O and O/O make the coat orange (formally called red) or cream except when dominant white is present. O/o causes tortoiseshell and calico fur. Since it is on the X chromosome, males can only have O or o, so all tortoiseshell and calico cats are either female or XXY.",
  "Brown": "b/b and b/bˡ cause chocolate coats, bˡ/bˡ causes cinnamon. B/B, B/b, B/bˡ cause black or gray coats unless Orange or White is present.",
  "Dilute": "D/D and D/d cause normal intensity of existing color. d/d lightens existing color. Turns black to gray (blue), orange (red) to cream, chocolate to lilac, cinnamon to fawn.",
  "Agouti": "A/A and A/a cause visible tabby markings unless the cat is solid white. a/a cats do not have tabby markings on non-orange fur. All orange fur has tabby markings.",
  "Colorpoint": "Cats with one or two copies of C do not show any form of colorpoint pattern. Cats with cˢ/cˢ or cˢ/c have the Siamese colorpoint pattern. cᵇ/cᵇ or cᵇ/c cause the sepia pattern of Burmese. cˢ/cᵇ causes mink colorpoint, and occurs in Siamese x Burmese crosses and Tonkinese. c/c causes complete albinism.",
  "Longhair": "L/L and L/l cause short hair, l/l causes long hair.",
}

// Maps regular colors to their dilute versions. 
export const dilutions : { [key: string]: string } = {
  "orange": "cream",
  "black": "gray", 
  "tortoiseshell": "dilute tortoiseshell",
  "calico": "dilute calico",
  "chocolate": "lilac",
  "cinnamon": "fawn",
  "white": "white", // no change 
}

// Maps allele pairs to the trait they cause (if not prevented by some other gene).
export const geneMappings : { [key: string]: string } = {
  "WDWD": "white", 
  "WDWh": "white", 
  "WDw": "white", 
  "WhWh": "bicolor", 
  "WhWl": "bicolor", 
  "Whw": "bicolor", 
  "WlWl": "bicolor", 
  "Wlw": "bicolor",
  "O": "orange",
  "OO": "orange",
  "Oo": "tortoiseshell", 
  "dd": "dilute", 
  "BB": "black",
  "Bb": "black",
  "Bbl": "black",
  "bb": "chocolate",
  "bbl": "chocolate",
  "blbl": "cinnamon",
  "AA": "tabby", 
  "Aa": "tabby", 
  "cscs": "colorpoint", 
  "csc": "colorpoint", 
  "cscb": "mink", 
  "cbcb": "sepia", 
  "cbc": "sepia", 
  "cc": "albino", 
  "LL": "shorthair",
  "Ll": "shorthair",
  "ll": "longhair",
}

export const traitMappings : { [key: string]: string[][]} = {
  "white": [["WD", "WD"], ["WD", "Wh"], ["WD", "Wl"], ["Wd", "w"]],
  "bicolor": [["Wh", "Wh"], ["Wh", "Wl"], ["Wh", "w"], ["Wl", "Wl"], ["Wl", "w"]],
  "non-white": [["w", "w"]],
  "chocolate": [["b", "b"], ["b", "bl"]],
  "lilac": [["b", "b"], ["b", "bl"]],
  "cinnamon": [["bl", "bl"]],
  "fawn": [["bl", "bl"]],
  "black": [["B", "B"], ["B", "b"], ["B", "bl"]],
  "non-brown": [["B", "B"], ["B", "b"], ["B", "bl"], ["b", "b"], ["b", "bl"], ["bl", "bl"]],
  "orange": [["O"]],
  "cream": [["O"]],
  "non-orange-xy": [["o"]],
  "non-orange-xx": [["o", "o"]],
  "tortoiseshell": [["O", "o"]],
  "dilute tortoiseshell": [["O", "o"]],
  "calico": [["O", "o"]],
  "tabby": [["A", "A"], ["A", "a"]], 
  "longhair": [["l", "l"]],
  "shorthair": [["L", "L"], ["L", "l"]], 
  "dilute": [["d", "d"]],
  "non-dilute": [["D", "D"], ["D", "d"]],
  "colorpoint": [["cs", "cs"], ["cs", "c"]],
  "mink": [["cs", "cb"]],
  "sepia": [["cb", "cb"], ["cb", "c"]],
  "albino": [["c", "c"]],
  "non-colorpoint": [["C", "C"], ["C", "cs"], ["C", "cb"], ["C", "c"]]
}